name = "2048-game"
main = "src/worker.js"

# Default production environment
compatibility_date = "2024-12-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
NODE_VERSION = "24"
ENVIRONMENT = "production"

# Preview environment for PR deployments
[env.preview]
# name will be set dynamically by CI/CD pipeline

[env.preview.vars]
NODE_VERSION = "24"
ENVIRONMENT = "preview"

# Production environment
[env.production]
name = "2048-game"

[env.production.vars]
NODE_VERSION = "24"
ENVIRONMENT = "production"

[[env.production.routes]]
pattern = "2048.harunon.club/*"
zone_name = "harunon.club"
