name = "2048-game"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.preview]
name = "2048-game-preview"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.preview.site]
bucket = "./dist"

[env.production]
name = "2048-game-prod"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.production.site]
bucket = "./dist"
