name = "2048-game"
main = "src/worker.js"

# Default production environment
compatibility_date = "2024-12-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
NODE_VERSION = "24"
ENVIRONMENT = "production"

# Preview environment for PR deployments
[env.preview]
name = "2048-game-preview"

[env.preview.vars]
NODE_VERSION = "24"
ENVIRONMENT = "preview"
