name: "Setup Node.js and Dependencies"
description: "Setup Node.js environment and install pnpm dependencies with caching"

inputs:
  node-version:
    description: "Node.js version to use (optional, will use .node-version file by default)"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "Whether pnpm cache was hit"
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: ".node-version"

    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v2.4.0
      with:
        version: 10

    - name: Cache pnpm store
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.pnpm-store
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-

    - name: Cache build artifacts
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          dist
          .vite
        key: build-${{ runner.os }}-${{ hashFiles('src/**/*', 'pnpm-lock.yaml') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
