name: "Setup Node.js and Dependencies"
description: "Setup Node.js environment and install npm dependencies with caching"

inputs:
  node-version:
    description: "Node.js version to use (optional, will use .node-version file by default)"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "Whether npm cache was hit"
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".node-version"
        cache: "npm"

    - name: Cache build artifacts
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          dist
          .vite
        key: build-${{ runner.os }}-${{ hashFiles('src/**/*', 'package-lock.json') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: npm ci
