name: "Setup Node.js and Dependencies"
description: "Setup Node.js environment and install npm dependencies with caching"

inputs:
  node-version:
    description: "Node.js version to use (optional, will use .node-version file by default)"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "Whether npm cache was hit"
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: ".node-version"
        cache: "npm"

    - name: Cache build artifacts
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          dist
          .vite
        key: build-${{ runner.os }}-${{ hashFiles('src/**/*', 'package-lock.json') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: npm install --ignore-scripts
