name: "Setup Node.js and Dependencies"
description: "Setup Node.js environment and install pnpm dependencies with caching"

inputs:
  node-version:
    description: "Node.js version to use (optional, will use .node-version file by default)"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "Whether pnpm cache was hit"
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: ".node-version"

    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Cache pnpm store
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.pnpm-store
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-

    - name: Cache build artifacts
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          dist
          .vite
        key: build-${{ runner.os }}-${{ hashFiles('src/**/*', 'pnpm-lock.yaml') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
