name: "Setup Node.js and Dependencies"
description: "Setup Node.js environment and install pnpm dependencies with caching"

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@15673661092cf7b14500f86491c4e807bf3cd4b8 # v3.5.1
      with:
        install: true
        cache: true

    - name: Cache pnpm store
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.pnpm-store
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-

    - name: Cache build artifacts
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          dist
          .vite
        key: build-${{ runner.os }}-${{ hashFiles('src/**/*', 'pnpm-lock.yaml') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
