name: Deploy to Production

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Test and Build
        uses: ./.github/actions/test-and-build
        with:
          run-e2e: "true"

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Load production secrets
        id: load-secrets
        uses: ./.github/actions/load-1password-secrets
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Build for deployment
        uses: ./.github/actions/test-and-build
        with:
          skip-tests: "true"

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ steps.load-secrets.outputs.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ steps.load-secrets.outputs.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy -e production
