name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Test and Build
        uses: ./.github/actions/test-and-build
        with:
          run-e2e: "true"

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load production secrets
        uses: ./.github/actions/load-1password-secrets
        with:
          environment: "2048game"
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Build for deployment
        uses: ./.github/actions/test-and-build
        with:
          skip-tests: "true"

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy -e production
