name: Test 1Password Integration
on:
  push:
    branches: [feature/1password-secrets]
  workflow_dispatch:

jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Load development secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_ENVIRONMENT: "2048Game-Development"
          
      - name: Verify secrets loaded
        run: |
          echo "Cloudflare Token: ${CLOUDFLARE_API_TOKEN:0:10}..."
          echo "Cloudflare Account: ${CLOUDFLARE_ACCOUNT_ID:0:10}..."
          
          if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
            echo "✅ CLOUDFLARE_API_TOKEN loaded"
          else
            echo "❌ CLOUDFLARE_API_TOKEN failed"
            exit 1
          fi
          
          if [ -n "$CLOUDFLARE_ACCOUNT_ID" ]; then
            echo "✅ CLOUDFLARE_ACCOUNT_ID loaded"
          else
            echo "❌ CLOUDFLARE_ACCOUNT_ID failed"
            exit 1
          fi
          
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps
        
      - name: Build project
        run: npm run build
        
      - name: Test deployment (dry run)
        run: |
          echo "Would deploy with:"
          echo "  Token: ${CLOUDFLARE_API_TOKEN:0:10}..."
          echo "  Account: ${CLOUDFLARE_ACCOUNT_ID}"
          echo "  Command: npx wrangler deploy --dry-run -e development"
          # Uncomment once 1Password is set up:
          # npx wrangler deploy --dry-run -e development

  test-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Load production secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_ENVIRONMENT: "2048Game-Production"
          
      - name: Verify secrets loaded
        run: |
          echo "Cloudflare Token: ${CLOUDFLARE_API_TOKEN:0:10}..."
          echo "Cloudflare Account: ${CLOUDFLARE_ACCOUNT_ID:0:10}..."
          
          if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
            echo "✅ CLOUDFLARE_API_TOKEN loaded"
          else
            echo "❌ CLOUDFLARE_API_TOKEN failed"
            exit 1
          fi
          
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps
        
      - name: Build project
        run: npm run build
        
      - name: Test deployment (dry run)
        run: |
          echo "Would deploy with:"
          echo "  Token: ${CLOUDFLARE_API_TOKEN:0:10}..."
          echo "  Account: ${CLOUDFLARE_ACCOUNT_ID}"
          echo "  Command: npx wrangler deploy --dry-run -e production"
          # Uncomment once 1Password is set up:
          # npx wrangler deploy --dry-run -e production