name: Test 1Password Integration
on:
  push:
    branches: [feature/1password-secrets]
  workflow_dispatch:

jobs:
  test-secrets-loading:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load secrets for testing
        id: load-secrets
        uses: ./.github/actions/load-1password-secrets
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Build project
        run: npm run build

      - name: Test deployment (dry run)
        env:
          CLOUDFLARE_API_TOKEN: ${{ steps.load-secrets.outputs.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ steps.load-secrets.outputs.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Testing deployment configuration..."
          echo "Token available: $([ -n "$CLOUDFLARE_API_TOKEN" ] && echo "✅ Yes" || echo "❌ No")"
          echo "Account ID available: $([ -n "$CLOUDFLARE_ACCOUNT_ID" ] && echo "✅ Yes" || echo "❌ No")"

          # Dry run test to verify Wrangler works with loaded secrets
          if command -v wrangler &> /dev/null; then
            echo "Testing Wrangler configuration..."
            npx wrangler whoami
          else
            echo "Wrangler not available for testing"
          fi